### ISSUE TITLE
Is it possible to add the option to send the emote link instead?

### ISSUE THREAD

**Issue by Idelives** [Yentis/betterdiscord-emotereplacer#45]
Would it be possible to add a option that sends the link of the emote itself? 

Much like in its predecessor this option allowed to change the image size by just adding a extension to the image link, it also allowed a quick output in slow systems and slow connections.

Sorry to make this request I don't mean to put pressure in anyone, specially in these dates

**Comment by Yentis** [comment]
You can change the emote size by using modifiers, for example: `:emotename:.resize-128` which would resize it to 128px. See the readme for all available modifiers.
I won't be adding emotes sent as links because it would not work with modifiers, for that you can use https://betterdiscord.app/plugin/FreeEmojis
